### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by jxlabWzZ** [JiaoLab2021/SynDiv#2]
Hi, Can you provide some test data?  

We had run it 2 two days at the SynDiv_c steps without any results. 

We are looking for you reply

**Comment by duzezhen** [comment]
Of course, we will upload the test data tomorrow.

The code is still running, and if there is still CPU usage, it could be due to a large number of genomes or large-sized genomes, which require a long time to process. The step that usually takes longer is the `SynDiv_c cal` step.

Thank you very much for using `SynDiv` and for your question. We hope to stay in touch.

**Comment by duzezhen** [comment]
We have uploaded test data to the **test** folder. Good luck!

**Comment by jxlabWzZ** [comment]
Thank you for your help!

we still encounter error through the test data, and we have upload the log files.
[log.txt](https://github.com/JiaoLab2021/SynDiv/files/12189894/log.txt)

+++++++
We installed SynDiv with "mamba create -n syndiv -c bioconda -c conda-forge -c duzezhen syndiv samtools minimap2"
+++++++
The running commond is :
nohup /usr/bin/time -v SynDiv --threads 10 -r genome/Col.fa -c configuration.txt &>log.txt &

**Comment by duzezhen** [comment]
This issue occurs because the **test** data has very few coordinates to compare, resulting in the failure to generate some files. As a result, the `SynDiv_c cal` step throws an error. We have already resolved this problem in version `v1.0.5`. However, please note that `v1.0.4` works fine with your real data.

Currently, you can organize your configuration files based on the test data.

Regarding the problem with submitting the code to Conda and the server connectivity issue, we are experiencing some difficulties. We will soon update the version on Conda to synchronize it with the latest changes.

**Comment by duzezhen** [comment]
The latest version, `v1.0.5`, has already been upgraded on Conda. Please try installing the latest version of SynDiv and give it another go.

Best of luck to you!

**Comment by jxlabWzZ** [comment]
Thank you very much，we have successfully run it. 
![截屏2023-07-28 下午9 13 53](https://github.com/JiaoLab2021/SynDiv/assets/54127791/3728df1e-6ed1-404b-b939-27ec9743dc85)

++++
In addition，I didnot understand whether it is necessary to generate aligns/a.align files by using show-aligns; Since the mummer is very slow, we would like to adopt minimap2-PAF files.
++++

**Comment by duzezhen** [comment]
Due to the correspondence between two genomes in the aligns file, it is necessary to use the aligns file to convert coordinates from the reference genome to the two query genomes in the `SynDiv_c cal` step.

Of course, you can try using `minimap2` to generate `paf file`, then convert it to the mummer format using [`paf2delta`,](https://github.com/malonge/RagTag/blob/df751bfeacbf0d9529eb2a0c82b10684407db59e/ragtag_paf2delta.py#L110) and then generate the `aligns file`. This should theoretically work, although we have not tried it.

Thank you for your question. We will attempt to directly use the `paf file` for coordinate conversion in future versions.

**Comment by jxlabWzZ** [comment]
Hello, I have encountered new trouble；
I run SynDiv chromosomes by chromosomes, some can get normal results, but some of them report errors:

[2023-08-07 17:51:31,108] CMD: /home/wuzhongzi209/miniconda3/envs/Syndiv2/bin/SynDiv_c cal -t 32 -r /home/wuzhongzi209/syn/chr1/genome/d01hap1.fa --co
[2023-08-07 17:51:31,632] Error: Exit status is 1
[2023-08-07 17:51:31,632] Error: CMD -> /home/wuzhongzi209/miniconda3/envs/Syndiv2/bin/SynDiv_c cal -t 32 -r /home/wuzhongzi209/syn/chr1/genome/d01hap
[2023-08-07 17:51:31,632] Error: stderr -> [main::2023-08-07 17:51:31] You are using SynDiv (v1.0.3)

[main_cal::2023-08-07 17:51:31] Running ...
[main_cal::2023-08-07 17:51:31] Change Global Parameters ...
[main_cal::2023-08-07 17:51:31] debug: 0
[main_cal::2023-08-07 17:51:31] threads: 32
[main_cal::2023-08-07 17:51:31] readBuffer: 1 MB
[main_cal::2023-08-07 17:51:31] Parse Parameters ...
[main_cal::2023-08-07 17:51:31] Building Syntenic Coordinates Index ...
[main_cal::2023-08-07 17:51:31] Building Reference Genome Index ...
[build_fasta_index::2023-08-07 17:51:31] Compute the length of each chromosome in the reference genome.
[main_cal::2023-08-07 17:51:31] Calculating Syntenic Diversity ...
[calculate::2023-08-07 17:51:31] Calculate: reference
[calculate::2023-08-07 17:51:31] Calculate: b01hap1
[calculate::2023-08-07 17:51:31] Calculate: b01hap2
[calculate::2023-08-07 17:51:31] Calculate: b03hap1
[calculate::2023-08-07 17:51:31] Calculate: b03hap2
[calculate::2023-08-07 17:51:31] Calculate: d01hap2
[calculate::2023-08-07 17:51:31] Calculate: d03hap1
[calculate_run::2023-08-07 17:51:31] Error: 'd03hap1' is not present in sampleSampleSyriMap.
Command exited with non-zero status 1
        Command being timed: "SynDiv --threads 32 -r genome/d01hap1.fa -c configuration.txt"
        User time (seconds): 5669.86
        System time (seconds): 195.15
        Percent of CPU this job got: 225%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 43:25.73
        Average shared text size (kbytes): 0

**Comment by jxlabWzZ** [comment]
The d03hap1 is very similar with reference genome.

**Comment by duzezhen** [comment]
It is possible that the issue you encountered is due to the similarity between d03hap1 and the reference genome, resulting in certain chromosomes not having alignment coordinates in the `SynDiv` comparison. As a result, no files are generated for those chromosomes, causing the error in the `SynDiv_c cal` step where the corresponding files cannot be found. This issue is actually similar to the one with the test data. Upgrading to `v1.0.5` should help resolve this problem.

**Comment by duzezhen** [comment]
It is possible that the issue you encountered is due to the similarity between d03hap1 and the reference genome, resulting in certain chromosomes not having alignment coordinates in the SynDiv comparison. As a result, no files are generated for those chromosomes, causing the error in the SynDiv_c cal step where the corresponding files cannot be found. This issue is actually similar to the one with the test data. Upgrading to v1.0.5 should help resolve this problem.













--

杜泽臻




At 2023-08-07 21:43:37, "jxlabWzZ" ***@***.***> wrote:

The d03hap1 is very similar with reference genome.

**Comment by jxlabWzZ** [comment]
Thank you for your reply, I got it.

**Comment by duzezhen** [comment]
You're welcome!
